-- 기존 테이블, 시퀀스 삭제 (있을 경우 대비)
DROP TABLE RECIPE CASCADE CONSTRAINTS;
DROP TABLE RECIPE_CATEGORY CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_RECIPE;

-- 카테고리 테이블 생성
CREATE TABLE RECIPE_CATEGORY (
    CATEGORY_NO NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) NOT NULL
);

-- 레시피 테이블 생성
CREATE TABLE RECIPE (
    NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    CATEGORY_NO NUMBER,
    CREATE_AT TIMESTAMP DEFAULT SYSDATE,
    MODIFIED_AT TIMESTAMP DEFAULT SYSDATE,
    DEL_YN CHAR(1) DEFAULT 'N',
    FOREIGN KEY (CATEGORY_NO) REFERENCES RECIPE_CATEGORY(CATEGORY_NO)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_RECIPE;

-- 카테고리 더미 데이터
INSERT INTO RECIPE_CATEGORY VALUES (1, '한식');
INSERT INTO RECIPE_CATEGORY VALUES (2, '중식');
INSERT INTO RECIPE_CATEGORY VALUES (3, '양식');
INSERT INTO RECIPE_CATEGORY VALUES (4, '일식');

-- 레시피 더미 데이터
INSERT INTO RECIPE (NO, TITLE, CONTENT, CATEGORY_NO)
VALUES (SEQ_RECIPE.NEXTVAL, '찜닭', '닭, 감자, 당근, 양파 넣고 물 붓고 끓인 뒤 간장, 고추장, 설탕, 고춧가루 넣고 졸이다가 불린 당면 넣고 익혀 참기름 후추로 마무리.', 1);

INSERT INTO RECIPE (NO, TITLE, CONTENT, CATEGORY_NO)
VALUES (SEQ_RECIPE.NEXTVAL, '짜장면', '면 삶고, 돼지고기 볶아 양파랑 춘장 넣고 볶다가 물 붓고 끓여 전분 풀어 걸쭉하게 만든 뒤 면에 부어 먹기.', 2);

INSERT INTO RECIPE (NO, TITLE, CONTENT, CATEGORY_NO)
VALUES (SEQ_RECIPE.NEXTVAL, '파스타', '파스타 면 삶고, 올리브유에 마늘 볶다가 토마토 소스 넣고 끓인 뒤 삶은 면과 섞고 바질이나 치즈 뿌려 마무리.', 3);

INSERT INTO RECIPE (NO, TITLE, CONTENT, CATEGORY_NO)
VALUES (SEQ_RECIPE.NEXTVAL, '라멘', '면 삶고, 돼지고기 차슈 준비하고, 다시마·멸치 등으로 육수 우린 뒤, 간장 또는 미소로 맛내고, 삶은 면에 육수 붓고 차슈, 달걀, 파 등 올려 완성.', 4);

-- 저장
COMMIT;